[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
game = "EqVAXa5rQwRPzqs4HcHreyymgjFAmjBnSS4eaV6twFwv"
page-logger = "8A93pmBLBa6UBNGEtNV1jBwsus6P71dqX16boo1DvV5k"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/admin/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
